version: 0.1
log:
  level: debug
  # fields:
  #   service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  secret: lgbvanill2017
  headers:
    X-Content-Type-Options: [nosniff]
  # debug:
  #     addr: localhost:5001
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
# auth:
#   htpasswd:
#     realm: basic-realm
#     path: /etc/docker/registry/htpasswd
