version: "2"

services:
  jenkins-agent-2:
    image: hellgate75/CDSTACK_PROJECT_NAME-jenkins-agent-cdstack
    container_name: linux-agent-2-compose
    privileged: true
    restart: always
    domainname: cdnet
    hostname: linux-agent-2
    environment:
      - "SSH_KEY_FILES_TAR_GZ_URL=https://s3-eu-west-1.amazonaws.com/ftorelli-docker-configuration/continuous-delivery/jenkins/rsa-keys.tgz"
      - "GIT_USER_NAME=hellgate75"
      - "GIT_USER_EMAIL=hellgate75@gmail.com"
      - "DOCKER_DAEMON_ARGS=--insecure-registry nexus.cdnet:18999,nexus.cdnet:19000"
    volumes:
      - "jenkins_agent_data:/var/lib/docker"
      - "jenkins_agent_mvn_data:/home/jenkins/.m2"
      - "jenkins_agent_gradle_data:/home/jenkins/.gradle"
    ports:
      - "4223:22"
    ulimits:
      memlock: -1
    cap_add:
      - IPC_LOCK
      - SYS_ADMIN
    networks:
      pipeline-private-network:
        aliases:
          - linux-agent-2.cdnet
          - linux-agent-2
networks:
  pipeline-private-network:
    external:
      name: CDSTACK_PROJECT_NAME-cdmainstack_pipeline-private-network
volumes:
  jenkins_agent_data:
    external:
      name: samples_jenkins_agent_data
  jenkins_agent_mvn_data:
    external:
      name: samples_jenkins_agent_mvn_data
  jenkins_agent_gradle_data:
    external:
      name: samples_jenkins_agent_gradle_data
